[phases.setup]
nixPkgs = ['...', 'nano']

[phases.install]
cmds = [
    '...',
    'php artisan storage:link',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan event:cache',
    'php artisan migrate --force',
]
